Upgrade activemq init script to one bundled with 5.6.0

diff --git a/modules/activemq/templates/init/activemq b/modules/activemq/templates/init/activemq
--- a/modules/activemq/templates/init/activemq
+++ b/modules/activemq/templates/init/activemq
@@ -1,4 +1,20 @@
 #! /bin/sh
+#
+# activemq   Apache ActiveMQ Middleware Service
+#
+# chkconfig:    345 24 76
+#
+# description:  Apache ActiveMQ Middleware Service
+#
+### BEGIN INIT INFO
+# Provides:          activemq
+# Required-Start:    $remote_fs
+# Required-Stop:     $remote_fs
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Start daemon at boot time
+# Description:       Enable service provided by daemon.
+### END INIT INFO
 
 # ------------------------------------------------------------------------
 # Licensed to the Apache Software Foundation (ASF) under one or more
@@ -17,11 +33,14 @@
 # limitations under the License.
 # ------------------------------------------------------------------------
 
+# Source function library
+. /etc/init.d/functions
+
 # Application
 APP_NAME="activemq"
 APP_LONG_NAME="ActiveMQ Broker"
 ACTIVEMQ_HOME="/usr/share/activemq"
-ACTIVEMQ_ADMIN="/usr/bin/activemq-admin"
+ACTIVEMQ_ADMIN="/usr/share/activemq/bin/activemq-admin"
 
 # Wrapper
 WRAPPER_CMD="/usr/sbin/tanukiwrapper"
@@ -56,6 +75,8 @@ RUN_AS_USER=activemq
 
 # Do not modify anything beyond this point
 #-----------------------------------------------------------------------------
+
+RETVAL=0
 
 # Get the fully qualified path to the script
 case $0 in
@@ -318,7 +339,8 @@ checkUser() {
 
         # Still want to change users, recurse.  This means that the user will only be
         #  prompted for a password once.
-        su -m $RUN_AS_USER -c "$REALPATH $1"
+        su -s /bin/bash -m $RUN_AS_USER -c "$REALPATH $1"
+        RETVAL=$?
 
         # Now that we are the original user again, we may need to clean up the lock file.
         if [ "X$LOCKPROP" != "X" ]
@@ -334,7 +356,7 @@ checkUser() {
             fi
         fi
 
-        exit 0
+        exit $RETVAL
     fi
 }
 
@@ -378,37 +400,44 @@ testpid() {
 }
 
 console() {
-    echo "Running $APP_LONG_NAME..."
+    echo "Running $APP_NAME..."
     getpid
     if [ "X$pid" = "X" ]
     then
         COMMAND_LINE="$CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.syslog.ident=$APP_NAME wrapper.pidfile=$PIDFILE $ANCHORPROP $LOCKPROP"
         exec $COMMAND_LINE
     else
-        echo "$APP_LONG_NAME is already running."
+        echo "$APP_NAME is already running."
         exit 1
     fi
 }
  
 start() {
-    echo "Starting $APP_LONG_NAME..."
+    echo -n "Starting $APP_NAME: "
     getpid
     if [ "X$pid" = "X" ]
     then
         COMMAND_LINE="$CMDNICE $WRAPPER_CMD $WRAPPER_CONF wrapper.syslog.ident=$APP_NAME wrapper.pidfile=$PIDFILE wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $LOCKPROP"
-        exec $COMMAND_LINE
+        $COMMAND_LINE
+        RETVAL=$?
+        success $"$base startup"
+        [ $RETVAL -eq 0 ] && success $"$base startup" || failure $"$base startup"
+        echo
+        exit $RETVAL 
     else
-        echo "$APP_LONG_NAME is already running."
+        failure "$APP_NAME is already running."
+        echo
         exit 1
     fi
 }
  
 stopit() {
-    echo "Stopping $APP_LONG_NAME..."
+    echo -n "Stopping $APP_NAME: "
     getpid
     if [ "X$pid" = "X" ]
     then
-        echo "$APP_LONG_NAME was not running."
+        failure "$APP_NAME was not running."
+        echo
     else
         if [ "X$IGNORE_SIGNALS" = "X" ]
         then
@@ -417,7 +446,8 @@ stopit() {
             if [ $? -ne 0 ]
             then
                 # An explanation for the failure should have been given
-                echo "Unable to stop $APP_LONG_NAME."
+                failure "Unable to stop $APP_NAME."
+                echo
                 exit 1
             fi
         else
@@ -425,7 +455,8 @@ stopit() {
             if [ -f $ANCHORFILE ]
             then
                 # An explanation for the failure should have been given
-                echo "Unable to stop $APP_LONG_NAME."
+                failure "Unable to stop $APP_NAME."
+                echo
                 exit 1
             fi
         fi
@@ -443,7 +474,7 @@ stopit() {
             then
                 CNT=`expr $CNT + 1`
             else
-                echo "Waiting for $APP_LONG_NAME to exit..."
+                #echo "Waiting for $APP_LONG_NAME to exit..."
                 CNT=0
             fi
             TOTCNT=`expr $TOTCNT + 1`
@@ -457,10 +488,12 @@ stopit() {
         testpid
         if [ "X$pid" != "X" ]
         then
-            echo "Failed to stop $APP_LONG_NAME."
+            failure "Failed to stop $APP_NAME."
+            echo
             exit 1
         else
-            echo "Stopped $APP_LONG_NAME."
+            success "Stopped $APP_NAME."
+            echo
         fi
     fi
 }
@@ -469,30 +502,31 @@ status() {
     getpid
     if [ "X$pid" = "X" ]
     then
-        echo "$APP_LONG_NAME is not running."
+        echo "$APP_NAME is not running."
         exit 1
     else
-        echo "$APP_LONG_NAME is running ($pid)."
+        echo "$APP_NAME is running ($pid)."
         exit 0
     fi
 }
 
 dump() {
-    echo "Dumping $APP_LONG_NAME..."
+    echo "Dumping $APP_NAME..."
     getpid
     if [ "X$pid" = "X" ]
     then
-        echo "$APP_LONG_NAME was not running."
+        echo "$APP_NAME was not running."
 
     else
         kill -3 $pid
 
         if [ $? -ne 0 ]
         then
-            echo "Failed to dump $APP_LONG_NAME."
+            echo "Failed to dump $APP_NAME."
             exit 1
         else
-            echo "Dumped $APP_LONG_NAME."
+            echo "Dumped $APP_NAME."
+            exit 0
         fi
     fi
 }
@@ -505,6 +539,8 @@ case "$1" in
         ;;
 
     'start')
+        mkdir -p ${PIDDIR}
+        chown ${RUN_AS_USER}:${RUN_AS_USER} ${PIDDIR}
         checkUser $1 touchlock
         start
         ;;
@@ -521,6 +557,7 @@ case "$1" in
         ;;
 
     'status')
+        checkUser $1
         status
         ;;
 
@@ -528,11 +565,10 @@ case "$1" in
         checkUser $1
         dump
         ;;
-
     *)
         echo "Usage: $0 { console | start | stop | restart | status | dump }"
-        exit 1
+        RETVAL=1
         ;;
 esac
 
-exit 0
+exit $RETVAL
